// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorCaixa.Infraestrutura.Persistencia;

#nullable disable

namespace SimuladorCaixa.Infraestrutura.Migrations
{
    [DbContext(typeof(SimuladorCaixaDbContext))]
    partial class SimuladorCaixaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("SimuladorCaixa.Dominio.Entidades.ProdutoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("PrazoMaximoMeses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prazo_maximo_meses");

                    b.Property<int>("PrazoMinimoMeses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prazo_minimo_meses");

                    b.Property<decimal>("RentabilidadeAnual")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("rentabilidade_anual");

                    b.Property<int>("Risco")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risco");

                    b.Property<int>("TipoProduto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_produto");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_maximo");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.HasIndex("TipoProduto")
                        .HasDatabaseName("ix_produtos_tipo_produto");

                    b.ToTable("produtos_investimento", (string)null);
                });

            modelBuilder.Entity("SimuladorCaixa.Dominio.Entidades.SimulacaoInvestimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataSimulacaoUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_simulacao_utc");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prazo_meses");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<int>("TipoProduto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_produto");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_final");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_simulacoes_cliente_id");

                    b.HasIndex("DataSimulacaoUtc")
                        .HasDatabaseName("ix_simulacoes_data");

                    b.HasIndex("ProdutoId");

                    b.ToTable("simulacoes_investimento", (string)null);
                });

            modelBuilder.Entity("SimuladorCaixa.Dominio.Entidades.SimulacaoInvestimento", b =>
                {
                    b.HasOne("SimuladorCaixa.Dominio.Entidades.ProdutoInvestimento", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
